### ISSUE TITLE
ROS Integration?

### ISSUE THREAD

**Issue by cmower** [wenbowen123/BundleTrack#51]
Hi @wenbowen123, is this integrated with or is there plans to integrate with ROS?

**Comment by robertokcanale** [comment]
I need it too! 

Is there any integration just with a simple/real camera?

**Comment by wenbowen123** [comment]
@robertokcanale @cmower 
For now, it does not support ROS yet. We may update it some time later. Stay tuned.

**Comment by raghavauppuluri13** [comment]
@cmower @robertokcanale I added code to integrate the realtime tracking with ROS melodic in [my fork](https://github.com/raghavauppuluri13/BundleTrack). I wasn't able to fully test it because I have an unsupported GPU (3080), but feel free to try it out after adapting code in the `src/tracker_node.cpp` file.

**Comment by kurshakuz** [comment]
@raghavauppuluri13 were you able to test it out?
